export const Phase = {
  TITLE: 'TITLE',
  INTRO: 'INTRO',
  IDLE: 'IDLE',
  THOUGHT: 'THOUGHT',
  RANDOM_EVENT: 'RANDOM_EVENT',
  EMPLOYEE_ENTER: 'EMPLOYEE_ENTER',
  EMPLOYEE_DIALOG: 'EMPLOYEE_DIALOG',
  EMPLOYEE_EXIT: 'EMPLOYEE_EXIT',
  RELEASING: 'RELEASING',
  GAME_OVER: 'GAME_OVER',
  VICTORY: 'VICTORY',
};
